### DISCUSSION TITLE
JesterJ CLI?

### DISCUSSION THREAD

**Discussion by janhoy** [nsoft/jesterj#202] [Q&A]
This framework seems capable, but I was surprised to find you need to compile Java to use it? Have you thought of making a CLI and a config file format to let users get started right away, and only power use cases would need to compile Java?

E.g.
```yaml
cat << EOF | bin/jesterj --
jesterj:
  inputs:
    - type: fs
      folder: C:\foo
      depth: 3
  output:
    solr:
      url: http://localhost:8983/solr/myCollection
```
